apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - postgres/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - observability/otel-lgtm.yaml
  - observability/mailpit.yaml
  - product-service/configmap.yaml
  - product-service/deployment.yaml
  - product-service/service.yaml
  - gateway/product-service-ingress.yaml
  - gateway/plugins.yaml
configMapGenerator:
  - name: keycloak-realm
    namespace: platform
    files:
      - keycloak/realm/product-service-realm.json
  - name: grafana-alerting
    namespace: platform
    files:
      - observability/grafana/alerting/product-service-alerts.yaml
