CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2)           NOT NULL,
    stock       INTEGER                  NOT NULL,
    sku         VARCHAR(50)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);
